In [4]:
import spacy
!python -m spacy download en_core_web_md

     ---------------------------------------- 0.0/33.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/33.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/33.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/33.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/33.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/33.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/33.5 MB ? eta -:--:--
     ---------------------------------------- 0.3/33.5 MB ? eta -:--:--
      -------------------------------------- 0.5/33.5 MB 882.6 kB/s eta 0:00:38
     - -------------------------------------- 1.0/33.5 MB 1.4 MB/s eta 0:00:24
     - -------------------------------------- 1.3/33.5 MB 1.5 MB/s eta 0:00:22
     -- ------------------------------------- 1.8/33.5 MB 1.7 MB/s eta 0:00:19
     -- ------------------------------------- 2.4/33.5 MB 1.8 MB/s eta 0:00:18
     --- -------------------

In [20]:
#sentimental analysis
import spacy
nlp=spacy.load('en_core_web_md')

In [11]:
nlp(u'lion').vector

array([-0.76275  , -0.2074   ,  0.32124  , -0.45817  , -0.36041  ,
        0.60152  ,  0.74492  ,  0.079701 , -0.23428  ,  0.31224  ,
       -0.43189  ,  0.20746  , -0.40774  , -0.2538   , -0.12308  ,
       -0.39652  ,  0.2361   ,  0.20473  ,  0.49645  ,  0.26983  ,
       -0.45623  ,  0.20879  , -0.0027486,  0.050435 , -0.003348 ,
       -0.088146 , -0.53855  ,  0.42507  , -0.70535  , -0.31984  ,
       -0.56023  , -0.042877 ,  0.31083  , -0.23038  ,  0.43657  ,
        0.18436  ,  0.52997  , -0.1038   ,  0.010579 ,  0.5373   ,
       -0.64911  ,  0.15171  , -0.13305  , -0.17798  ,  0.083277 ,
       -0.15615  , -0.1446   , -0.27032  ,  0.19693  ,  0.22867  ,
       -0.5745   ,  0.16468  ,  0.029028 ,  0.66735  , -0.13859  ,
        0.51194  , -0.029928 ,  0.11792  , -0.15589  ,  0.69151  ,
        0.19838  ,  0.032428 ,  0.37526  ,  0.099998 , -0.48631  ,
       -0.13605  ,  0.5295   , -0.089214 ,  0.34458  ,  0.19393  ,
        0.012607 , -0.1999   , -0.38105  , -0.05991  , -0.8103

In [12]:
doc=nlp(u"the quick brown fo jumped over the lazy dogs.")
doc.vector

array([-7.16381013e-01, -1.63229890e-02, -2.13782400e-01, -2.77799014e-02,
        5.10271406e-03,  1.60797015e-02, -2.41301022e-02, -1.66455790e-01,
        8.93550068e-02,  1.77834821e+00, -4.45870049e-02, -3.63248959e-02,
       -8.66516121e-03, -4.41019842e-03, -8.20313245e-02,  8.22900012e-02,
       -7.44889155e-02,  9.26726997e-01, -1.30594000e-01, -2.01024100e-01,
       -1.58771984e-02,  3.95413004e-02,  8.83492008e-02, -2.61575997e-01,
       -8.37433934e-02, -1.56619698e-01, -3.90259027e-02, -8.83080363e-02,
       -1.98695064e-02, -2.87451982e-01, -2.18694180e-01,  2.77088493e-01,
        6.44630939e-02, -1.02154031e-01,  2.01056093e-01,  9.66349989e-02,
       -1.07731201e-01, -4.44939062e-02, -2.30556577e-01,  1.11496791e-01,
        5.22767119e-02,  3.11437994e-02, -1.23784028e-01,  2.01593041e-02,
        2.30333894e-01, -4.64029014e-02, -5.93701005e-02, -1.97779965e-02,
        1.08657954e-02, -2.73632016e-02, -1.70822784e-01,  2.03892395e-01,
       -2.24663001e-02, -

In [14]:
tokens=nlp(u'lion cat pet')
tokens

lion cat pet

In [15]:
for token1 in tokens:
    for token2 in tokens:
        print(token1.text,token2.text,token1.similarity(token2))

lion lion 1.0
lion cat 0.31077107787132263
lion pet 0.31077107787132263
cat lion 0.31077107787132263
cat cat 1.0
cat pet 1.0000001192092896
pet lion 0.31077107787132263
pet cat 1.0000001192092896
pet pet 1.0


In [17]:
nlp(u'lion').similarity(nlp(u'dandelion'))

0.344340443611145

In [25]:
tokens=nlp(u'like love hate')
tokens

like love hate

In [26]:
for token1 in tokens:
    for token2 in tokens:
        print(token1.text,token2.text,token1.similarity(token2))

like like 1.0
like love 1.0
like hate 1.0
love like 1.0
love love 1.0
love hate 1.0
hate like 1.0
hate love 1.0
hate hate 1.0


In [27]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Home\AppData\Roaming\nltk_data...


True

In [30]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid=SentimentIntensityAnalyzer()

In [31]:
a='this is a good movie'
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.508, 'pos': 0.492, 'compound': 0.4404}

In [32]:
a='this was the best,most awesom movie ever made!!!'
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}

In [33]:
a='this was the worst film to ever disgrace the screen'
sid.polarity_scores(a)

{'neg': 0.477, 'neu': 0.523, 'pos': 0.0, 'compound': -0.8074}

In [55]:
a='navin is neither ugly nor beautiful'
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.431, 'pos': 0.569, 'compound': 0.6474}

In [65]:
import numpy as np
import pandas as pd
df=pd.read_csv(r'amazonreviews.tsv',sep='\t')
df.head()

label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [67]:
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [69]:
df.dropna(inplace=True)

In [71]:
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [73]:
blanks=[]
for i,lb,rv in df.itertuples():
    if type(rv)==str:
        if rv.isspace():
            blanks.append(i)
df.drop(blanks,inplace=True)
df['label'].value_counts()


label
neg    5097
pos    4903
Name: count, dtype: int64

In [74]:
sid.polarity_scores(df.loc[0]['review'])
df.loc[0]['label']

'pos'

In [75]:
df['scores']=df['review'].apply(lambda review:sid.polarity_scores(review))
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...

In [77]:
df['compound']=df['scores'].apply(lambda score_dict:score_dict['compound'])
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  compound  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...    0.9454  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...    0.8957  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...    0.9858  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...    0.9814  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...    0.9781

In [78]:
sid.polarity_scores(df.loc[0]['review'])
df.loc[0]['scores']

{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'compound': 0.9454}

In [81]:
df['comp_score']=df['compound'].apply(lambda c:'pos' if c>=0 else 'neg')
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  compound comp_score  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...    0.9454        pos  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...    0.8957        pos  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...    0.9858        pos  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...    0.9814        pos  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...    0.9781        pos

In [83]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy_score(df['label'],df['comp_score'])

0.7097

In [84]:
print(confusion_matrix(df['label'],df['comp_score']))

[[2629 2468]
 [ 435 4468]]


In [85]:
print(classification_report(df['label'],df['comp_score']))

              precision    recall  f1-score   support

         neg       0.86      0.52      0.64      5097
         pos       0.64      0.91      0.75      4903

    accuracy                           0.71     10000
   macro avg       0.75      0.71      0.70     10000
weighted avg       0.75      0.71      0.70     10000

